### ISSUE TITLE
lightbox modal not showing properly

### ISSUE THREAD

**Issue by alvinmactal** [MurhafSousli/ngx-gallery#256]
hi im using lighbox and the modal is not showing property. it is showing in the bottom of the page

**Comment by MurhafSousli** [comment]
Closing as does not follow the template issue

**Comment by Revii** [comment]
@alvinmactal You need to add cdk styles to your project.
@MurhafSousli It can be good idea to add this information to doc.

**Comment by mbrookson** [comment]
I'm having this issue too since upgrading to 4.x, the lightbox overlay is being displayed at the bottom of the rest of the site's content.

It seems that the cdk styles are not being imported by default anymore and this is not in the documentation as far as I can tell.

How do I import the styles from cdk and make the overlay actually overlay the content?

Thanks

**Comment by MurhafSousli** [comment]
@mbrookson  here you go https://material.angular.io/cdk/overlay/overview

Just add this line in your global style

```css
@import '~@angular/cdk/overlay-prebuilt.css';
```

**Comment by arashbi** [comment]
I added the import as mentioned. But still have problem with lightbox
https://stackblitz.com/edit/angular-hbhbjf
