### ISSUE TITLE
Unable to load Image!

### ISSUE THREAD

**Issue by sunildipun** [MurhafSousli/ngx-gallery#271]
@

#### What is the expected behavior?
Image Preview should show up when i clicking an image.

#### What is the current behavior?
In Preview i am getting an exclamation mark and Unable to load image!

#### Which versions are you using for the following packages?

Angular:
Angular CDK: ^6.4.7
Angular CLI: ~6.0.8
Typescript: ^2.9.2
Gallery: 
 "@ngx-gallery/core": "^4.0.2-beta.0",
    "@ngx-gallery/gallerize": "^4.0.2-beta.0",
    "@ngx-gallery/lightbox": "^4.0.2-beta.0",

**Comment by GitHubish** [comment]
I have the same problem.
GalleryModule and LightboxModule are loaded into app.module and I use the lightbox in a lazy loading child module.

Another important point and I think that is where the problem lies. I have an interceptor. 
My initial problem was that GalleryModule and LightboxModule were loaded directly into the child module (lazy). It worked without any problems. But the problem I have is that probably this has an impact on my interceptor that is declared in the app.module. No problem with GET requests, the interceptor processes them but not POST requests which is very problematic. I have tested different ways in the GalleryModule configuration options to change the loading mode but this does not solve my problem.

Any ideas?

**Comment by MurhafSousli** [comment]
Use `intermediate` mode for loading the images
