### ISSUE TITLE
Interceptor not called in lazy-loading module with imported GalleryModule

### ISSUE THREAD

**Issue by uncleGera** [MurhafSousli/ngx-gallery#277]
#### What is the current behavior?
When I importing the GalleryModule in lazy-loading module my interceptor stops working in this module. I suppose that happens because I use the HttpClientModule in AppModule and in GalleryModule also used HttpClientModule. But I should import HttpClientModule only once, see [docs](https://angular.io/guide/http#setup-installing-the-module)

What can I do to resolve this problem?

#### Which versions are you using for the following packages?

Angular: 7.0.0
Angular CDK: 7.1.0
Angular CLI: 7.0.2
Typescript: 3.1.1
Gallery: 4.0.2-beta.0

**Comment by MurhafSousli** [comment]
Hi @alex-gera can you make a repro [stackblitz](https://stackblitz.com/edit/ngx-gallery)

**Comment by hpawe01** [comment]
@uncleGera: Are you still having issues with your interceptors?

I fixed this by implementing a `forRoot` method in my `CoreModule`:
```typescript
 static forRoot(): ModuleWithProviders {
    return {
      ngModule: CoreModule,
      providers: [
        [{ provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true }]
      ],
    };
  }
```
and call it in my `AppModule`:
```typescript
  imports: [
    // ...
    CoreModule.forRoot(),
   // ...
  ],
```

**Comment by kornect** [comment]
Getting a similar issue too, all my apis calls are returning 401 as the auth interceptor is overwritten.
@hpawe01 I tried your solution but this does not seem to work on lazy modules. Do you have lazy modules that import the gallery module?

**Comment by mishkamishka47** [comment]
Something that seems to have worked for me was to isolate the components that need the gallery into their own lazy-loaded module rather than importing it in `AppModule` or some other core module. The `HttpClientModule` and its interceptors get overwritten in that module, but the other modules retain the one with the interceptors that I defined. Of course, if you need both your own interceptors and the gallery within the same module, this approach won't work, but hopefully it'll help someone else out.

```
AppModule
  | import HttpClientModule
  | define HttpInterceptors
AppRoutingModule
  | lazy load ImagesModule
ImagesModule
  | import GalleryModule
    | (imports HttpClientModule and overwrites for ImagesModule)
```

This is just a lucky workaround in my case. This package still should not be importing its own `HttpClientModule`.
