### ISSUE TITLE
If I want show more 400 images ngx-gallery doesn't work

### ISSUE THREAD

**Issue by mihalskiy** [MurhafSousli/ngx-gallery#294]
1. http://skrinshoter.ru/p/090819/8NNuvP

**Comment by aslubsky** [comment]
+1 looks like DOM issue

**Comment by MurhafSousli** [comment]
This is a very old issue, yes, This gallery won't work properly for 400 images, the current solution does not support a large set of images because each image width is reserved and the browser has a maximum width for DOM to set which cannot be exceeded (slider width = 400 x viewport width). I suggest using up to 30 images

**Comment by aslubsky** [comment]
Got it, thanks. I guess you should add this this note/warning to your readme, because it was unexpected and found on prod((( I known that it's opensource and etc, but people should known this limitation before usage, I guess

**Comment by MurhafSousli** [comment]
@aslubsky Added a note to the wiki
