### ISSUE TITLE
loadingStrategy applied also to thumb

### ISSUE THREAD

**Issue by bierzorutas** [MurhafSousli/ngx-gallery#513]
Hi,
first of all thanks for your work and your time in this project.

After use your library long time, I am in the process of need a lazy load due a case of a big gallery (over 300 images), after try to use loadingStrategy with 'lazy', seems to me that is not well implemented or not well understood by me.

Even using lazy as strategy, all thumbnails are loaded initially on first image opened, even thumbnails not visible. Would be possible that not visible thumbs are not loaded ?

I would suggest the usage of 
_[preRender]="false"
(deferLoad)="thumb.show = true"_
thumb gallery container.

together with 
_*ngIf="thumb.show"_
in img element: 

Kind regards

**Comment by MurhafSousli** [comment]
Thanks for the nice words and sorry for the belated response!

I am slowly moving into using virtual scroll but it is more complex than it seems when applied to a gallery, especially when considering keeping some features like auto-size.

The current lazy feature works well for the main slide because we only have a single item at a time so it is easier to know which and how many elements to render, but when it comes to thumbnails, you might have 4, 10 or 20 to be shown and you have to write the proper logic for different use cases.

So yea, the lazy feature is not applied to thumbnails at the moment.. but we can try another trick with the new img attribute `loading="lazy"`

https://github.com/MurhafSousli/ngx-gallery/blob/a65f28b9aa913290dba21ee5b4d535f451225887/projects/ng-gallery/src/lib/components/templates/gallery-image.component.ts#L27-L32

When using this, the thumbnails will still render, however, the images will only get fetched within the viewport.

**Comment by MurhafSousli** [comment]
Please try v8.0.2 and see if that helps!
