### ISSUE TITLE
Lightbox gallery overlay close button is clicking behind

### ISSUE THREAD

**Issue by deokey** [MurhafSousli/ngx-gallery#54]
```
- [X] bug report
```

### OS and Version
macOS (high sierra), osX ( v9, v11)
### Versions
Angular CLI: 1.6.2
Node: 9.3.0
OS: darwin x64
Angular: 5.2.0
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, platform-server
... router

@angular/animations: 5.2.1
@angular/cdk: 5.1.0
@angular/cli: 1.6.2
@angular/flex-layout: 2.0.0-beta.12
@angular/language-service: 5.2.1
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.40
@angular-devkit/core: 0.0.27
@angular-devkit/schematics: 0.0.50
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.15
@schematics/schematics: 0.0.15
typescript: 2.4.2
webpack: 3.10.0

### Repro steps

Open the lightbox gallery on any device (it will open the overlay gallery) then try to close the gallery clicking the close button (the default red circle shaped button with an X). There is que thing, if i have any link or clickable item (even the image that triggers the lightbox gallery) behind the overlay it will do a click on that thing, like its going through the button and the overlay so its clicking the item behind.

in this case, it has the log out button behind so when i close the lightbox im logged out.
![gifdesktop](https://user-images.githubusercontent.com/18384611/35301477-00446a96-0062-11e8-9e39-fa0a058d6365.gif)

in this case, i have the hamburger icon to toggle the side menu and then i close the gallery toggles on the side menu.
![gifmobile](https://user-images.githubusercontent.com/18384611/35301478-005a6666-0062-11e8-8e37-1f983e671aa3.gif)

**Comment by gabitoesmiapodo** [comment]
Same here.

**Comment by MurhafSousli** [comment]
Hey guys, I tried to reproduce the issue. but I couldn't
Can you help on a reproduction?
Here is a [stackblitz with toolbar button](https://stackblitz.com/edit/ngx-gallery-g6mujf?file=app%2Fapp.component.ts)

**Comment by gabitoesmiapodo** [comment]
Hi, the problem seems to be that you have to scroll down to click "Open Lightbox". That makes the header go up, so the "Click me" button is not behind the lightbox's close button anymore.

That's more or less what happens to me, at least: you tap whatever is behind the close button on mobile devices, because of a slight delay in the button press.

In my case, it is a typical Bootstrap 3 + Angular 2 site, so no Material Design Components, or anything.

I modified your example slightly to resemble what I have in my project: https://stackblitz.com/edit/ngx-gallery-jcmqra?file=app/app.component.html

If you open https://ngx-gallery-jcmqra.stackblitz.io on a mobile device, or the Chrome mobile devices emulation, you will be able to reproduce the problem (it seems to be OK in desktop).

<img width="334" alt="1" src="https://user-images.githubusercontent.com/4015436/36789801-8f8e0ec0-1c71-11e8-9059-470f398bb351.png">

<img width="332" alt="2" src="https://user-images.githubusercontent.com/4015436/36789830-ab005208-1c71-11e8-806a-b70bb0206666.png">

<img width="591" alt="3" src="https://user-images.githubusercontent.com/4015436/36789842-b63b7468-1c71-11e8-9664-affc16091542.png">

**Comment by deokey** [comment]
Hi guys,
As gabitoesmiapodo said it only triggers while using the device toolbar (emulating a mobile phone on browser), the date i posted the bug in my webpage looked like the gifs i shared in the first comment, today in my page only can reproduce the bug using the device toolbar, maybe you updated something to fix it on desktop as gabitoesmiapodo describes.

also used your example adding it the fixed bar like my webpage
https://ngx-gallery-gc1snc.stackblitz.io/

without the fixed bar, make sure you scroll enough to position the "click me" button behind the close button on the lightbox gallery.
https://ngx-gallery-gdut7e.stackblitz.io
